import {Suspense} from 'react'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FaFacebookF, FaInstagram, FaTiktok, FaTelegramPlane, FaYoutube } from "react-icons/fa";
import "./globals.css";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import { fetchCategoriesAndBrands } from '@/utils/fetchData';
import StoreProvider from './providers';
import Footer from '@/components/Footer';
import SkeletonFilterProductList from '@/features/products/components/SkeletonProductFilter';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const dynamicData = await fetch(`https://...`, { cache: "no-store" });

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { categories, brands } = await fetchCategoriesAndBrands();
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#f3f3f3]`}>
        <Suspense fallback={<SkeletonFilterProductList/>}>
          <StoreProvider>
            <Nav categories={categories} brands={brands}/>
            <div className='bg-white'>
              {children}
            </div>
            {/* <Footer/> */}
          </StoreProvider>
        </Suspense>
        </body>
    </html>
  );
}
